#!/bin/bash
# source <(curl -s https://raw.githubusercontent.com/NodersUA/Tools/main/subspace_wipe)

automate_subspace_wipe() {
    echo "y"
    sleep 1
    echo "n"
    sleep 1
    echo "y"
    sleep 1
    echo "n"
}
automate_subspace_wipe | subspace wipe
systemctl restart subspaced
